1		31.6	 snaps fingers	
2		48.1	 sighs	
3		61.5	 sighs	
4		103.0	 chuckles	
5		132.2	 sighs	
6		145.1	 door chimes	
7		149.2	 sighs	
8		219.9	 alarms blaring	
9		227.9	 monitor beeping	
10		231.5	 steady tone	
11		284.4	 door chimes	
12		309.0	 sighs	
13		367.9	 sighs	
14		425.1	 hissing	
15		467.7	 conversations and laughter	
16		481.6	 grunting	
17		486.3	 grunting	
18		501.6	 beeping	
19		514.9	 low growl	
20		555.5	 whoosh of active transport	
21		567.2	 whispering	
22		625.6	 sighs	
